name: ai_recording_visualizer
description: A Very Good Project created by Very Good CLI.
version: 1.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  audio_video_progress_bar: ^1.0.1
  bloc: ^8.1.2
  collection: ^1.18.0
  equatable: ^2.0.5
  file_picker: ^5.3.3
  firebase_dart:
    git:
      url: https://github.com/tomassasovsky/firebase_dart.git
      ref: fix/prefix-tojson-not-working
      path: packages/firebase_dart
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  media_kit: ^1.1.3+1
  media_kit_libs_linux: ^1.1.0
  media_kit_libs_macos_video: ^1.1.2
  media_kit_libs_windows_video: ^1.0.6
  media_kit_native_event_loop: ^1.0.7
  media_kit_video: ^1.1.3
  meta: ^1.9.1
  package_info: ^2.0.2
  path_provider: ^2.0.15
  platform_info: ^4.0.0
  secure_dotenv: ^1.0.0
  url_launcher: ^6.1.11

dependency_overrides:
  collection: ^1.17.2
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.3
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  msix: ^3.16.1
  secure_dotenv_generator: ^1.0.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

msix_config:
  display_name: AI Recording Visualizer
  identity_name: 23080TomsSasovsky.AIRecordingVisualizer
  publisher_display_name: Tomás Sasovsky
  publisher: CN=0614BB1B-E86A-4B59-BA5B-0E6934A8FF36
  languages: en-US, es-ES
  logo_path: assets/app_icon.png
  msix_version: 1.1.0.0
  certificate_path: cert/CERTIFICATE_AI_REC_VIS.pfx
  capabilites: internetClient
  store: true
