name: ai_recording_visualizer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  audio_video_progress_bar: ^1.0.1
  bloc: ^8.1.2
  collection: ^1.17.1
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  media_kit: ^0.0.9+1
  media_kit_libs_linux: ^1.0.2
  media_kit_libs_macos_video: ^1.0.5
  media_kit_libs_windows_video: ^1.0.2
  media_kit_native_event_loop: ^1.0.4
  media_kit_video: ^0.0.12
  meta: ^1.9.1

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.0
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
