name: ai_recording_visualizer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  audio_video_progress_bar: ^1.0.1
  bloc: ^8.1.2
  collection: ^1.17.1
  cross_file: ^0.3.3+4
  desktop_drop: ^0.4.1
  dotenv_gen:
    git:
      url: https://github.com/tomassasovsky/dotenv_gen.git
      path: dotenv_gen
  equatable: ^2.0.5
  file_picker: ^5.3.2
  firebase_dart:
    git:
      url: https://github.com/tomassasovsky/firebase_dart.git
      ref: fix/prefix-tojson-not-working
      path: packages/firebase_dart
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  media_kit: ^0.0.9+1
  media_kit_libs_linux: ^1.0.2
  media_kit_libs_macos_video: ^1.0.5
  media_kit_libs_windows_video: ^1.0.2
  media_kit_native_event_loop: ^1.0.4
  media_kit_video: ^0.0.12
  meta: ^1.9.1
  package_info: ^2.0.2
  path_provider: ^2.0.15
  platform_info: ^4.0.0
  url_launcher: ^6.1.11

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.4
  dotenv_gen_runner:
    git:
      url: https://github.com/tomassasovsky/dotenv_gen.git
      path: dotenv_gen_runner
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.0
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  msix: ^3.14.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

msix_config:
  display_name: AI Recording Visualizer
  identity_name: 23080TomsSasovsky.AIRecordingVisualizer
  publisher_display_name: Tomás Sasovsky
  publisher: CN=0614BB1B-E86A-4B59-BA5B-0E6934A8FF36
  languages: en-US, es-ES
  logo_path: assets/app_icon.png
  msix_version: 1.0.0.0
  certificate_path: cert/CERTIFICATE_AI_REC_VIS.pfx
  capabilites: internetClient
  store: true
