// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_dart/firebase_dart.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:flutter_dotenv/flutter_dotenv.dart' hide dotenv;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions currentPlatform(DotEnv dotEnv) {
    final webApiKey = dotEnv.get('FIREBASE_WEB_API_KEY');
    final webAppId = dotEnv.get('FIREBASE_WEB_APP_ID');

    final macosApiKey = dotEnv.get('FIREBASE_MACOS_API_KEY');
    final macosAppId = dotEnv.get('FIREBASE_MACOS_APP_ID');
    final macosClientId = dotEnv.get('FIREBASE_MACOS_CLIENT_ID');

    final windowsApiKey = dotEnv.get('FIREBASE_WINDOWS_API_KEY');
    final windowsAppId = dotEnv.get('FIREBASE_WINDOWS_APP_ID');

    final linuxApiKey = dotEnv.get('FIREBASE_LINUX_API_KEY');
    final linuxAppId = dotEnv.get('FIREBASE_LINUX_APP_ID');

    final fuchsiaApiKey = dotEnv.get('FIREBASE_FUCHSIA_API_KEY');
    final fuchsiaAppId = dotEnv.get('FIREBASE_FUCHSIA_APP_ID');

    final androidApiKey = dotEnv.get('FIREBASE_ANDROID_API_KEY');
    final androidAppId = dotEnv.get('FIREBASE_ANDROID_APP_ID');

    final iosApiKey = dotEnv.get('FIREBASE_IOS_API_KEY');
    final iosAppId = dotEnv.get('FIREBASE_IOS_APP_ID');
    final iosClientId = dotEnv.get('FIREBASE_IOS_CLIENT_ID');

    final messagingSenderId = dotEnv.get('FIREBASE_MESSAGING_SENDER_ID');
    final projectId = dotEnv.get('FIREBASE_PROJECT_ID');
    final measurementId = dotEnv.get('FIREBASE_MEASUREMENT_ID');

    final web = FirebaseOptions(
      apiKey: webApiKey,
      appId: webAppId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      authDomain: '$projectId.firebaseapp.com',
      storageBucket: '$projectId.appspot.com',
      measurementId: measurementId,
    );

    final android = FirebaseOptions(
      apiKey: androidApiKey,
      appId: androidAppId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: '$projectId.appspot.com',
    );

    final ios = FirebaseOptions(
      apiKey: iosApiKey,
      appId: iosAppId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: '$projectId.appspot.com',
      iosClientId: iosClientId,
      iosBundleId: 'com.example.aiRecordingVisualizer',
    );

    final macos = FirebaseOptions(
      apiKey: macosApiKey,
      appId: macosAppId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: '$projectId.appspot.com',
      iosClientId: macosClientId,
      iosBundleId: 'com.example.aiRecordingVisualizer.RunnerTests',
    );

    final windows = FirebaseOptions(
      apiKey: windowsApiKey,
      appId: windowsAppId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: '$projectId.appspot.com',
    );

    final linux = FirebaseOptions(
      apiKey: linuxApiKey,
      appId: linuxAppId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: '$projectId.appspot.com',
    );

    final fuchsia = FirebaseOptions(
      apiKey: fuchsiaApiKey,
      appId: fuchsiaAppId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: '$projectId.appspot.com',
    );

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        return fuchsia;
    }
  }
}
